# Generated by Django 5.1.4 on 2025-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('rule', models.BooleanField()),
                ('time_slots', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=20)),
            ],
        ),
    ]
